plugins {
    id 'io.github.qishr.cascara-gradle-plugins.ct' version '0.1.0'
    id 'io.github.qishr.cascara-gradle-plugins.vsix' version '0.1.0'
    id 'base'
}

// Useful gradle commands:
//    ./gradlew build
//    ./gradlew compileAllCt
//    ./gradlew packageVsix
//    ./gradlew installVsix
//    ./gradlew reinstallVsix
//    ./gradlew uninstallVsix

ct {
    formats {
        // When a configuration (e.g. 'retroAmber') for a format (e.g. ghostty)
        // doesn't specify an output filename, the output filename is assembled
        // based on the configuration name (e.g. 'retroAmber') changed into
        // -kebab-case- and the suffix is obtained from the format definition
        // (e.g. res://ghostty.tc)
        ghostty {
            retroAmber { entry = "retro-amber-on-bright-beige.ct"; }
            retroGreen { entry = "retro-green-on-bright-beige.ct"; }
        }

        iterm2 {
            retroAmber { entry = "retro-amber-on-bright-beige.ct"; }
            retroGreen { entry = "retro-green-on-bright-beige.ct"; }
        }

        vscode {
            retroAmberOnBrightBeige { entry = "retro-amber-on-bright-beige.ct"; }
            retroAmberOnDullBeige   { entry = "retro-amber-on-dull-beige.ct";   }
            retroAmberOnHeavyMetal  { entry = "retro-amber-on-heavy-metal.ct";  }
            retroGreenOnBrightBeige { entry = "retro-green-on-bright-beige.ct"; }
            retroGreenOnDullBeige   { entry = "retro-green-on-dull-beige.ct";   }
            retroGreenOnHeavyMetal  { entry = "retro-green-on-heavy-metal.ct";  }
        }
    }
}

vsix {
    name        = "cascara-retro-theme"
    displayName = "Cascara Retro Theme"
    description = "Retro theme pack for Visual Studio Code"
    version     = project.version.toString()
    publisher   = "Cascara"
    icon        = "images/icon.png"

    categories "Themes"

    engines = [
        "vscode": "^1.103.0"
    ]

    repository = [
        "type": "git",
        "url" : "git+https://github.com/sandydunlop/cascara-retro-theme.git"
    ]

    readme      = layout.projectDirectory.file("README.md")
    license     = layout.projectDirectory.file("LICENSE")
    changeLog   = layout.projectDirectory.file("CHANGELOG.md")
    imagesDir   = layout.projectDirectory.dir("src/main/resources/vscode/images")

    // Automatically pulls compiled output from cascara-gradle-plugins.ct
    themes.from(layout.buildDirectory.dir("themes/vscode"))
}

// Ensure execution flow
tasks.named('packageVsix') {
    dependsOn compileAllCt
}

tasks.named('build') {
    dependsOn tasks.named('packageVsix')
}
